### PR TITLE
added basic docker-file

### PR DESCRIPTION
**Pull request by senhorinfinito**
Added the docker-file and .dockerignore.  I'll improve over a period of the time.

### CODE REVIEW

**Comment by senhorinfinito** [comment]
@hardikdava  ,  any suggestions ?

**Comment by AyushExel** [comment]
Cam you also add the usage steps in the readme expandable section that is collapsed by default

**Comment by senhorinfinito** [comment]
Sure

**Comment by senhorinfinito** [comment]
> Cam you also add the usage steps in the readme expandable section that is collapsed by default

@AyushExel  Done.

**Comment by AyushExel** [comment]
Perfect thanks! Have you tested it with/without GPU as mentioned in the steps?

**Comment by senhorinfinito** [comment]
Without GPU not ran any command of trolo. 
But tested with GPU.

**Comment by AyushExel** [comment]
Can we just name it trolo instead of trolo-app? Or is there any reason for it

**Comment by senhorinfinito** [comment]
I'll revert to trolo only. I have added because of docker  env.

**Comment by senhorinfinito** [comment]
> Can we just name it trolo instead of trolo-app? Or is there any reason for it

Done.  changed to trolo

**Comment by AyushExel** [comment]
Thanks for your contribution

**Pull request merged**
