### PR TITLE
added demo colab notebooks

### PR DESCRIPTION
**Pull request by pks916**
any changes suggested?

### CODE REVIEW

**Comment by pks916** [comment]
first PR ever, please be lenient

**Comment by hardikdava** [comment]
@pks916 Please move all notebooks to its individual directory and don't forget to add python script and readme with details on how to install and use it. Also if you have used any external packages then mention their license. If licesnse does not perimit under Apache 2.0 or MIT then do not forget to mention it. I have already create a recipe for line counter. I will go through notebooks and let you know any changes.

**Comment by hardikdava** [comment]
@pks916 I have checked your provided notebooks. All of them are missing instructions and comments. You have to highlight more about `trolo` as we are trying to create these examples for user about how they can use `trolo` for various downstream tasks.

**Comment by pks916** [comment]
can they all be merged into a single example, like you mixed tracking and object passing line counter, just adding csv Sink should do the other one left?

**Pull request closed without merging**
