### PR TITLE
Video writing with supervision

### PR DESCRIPTION
**Pull request by hardikdava**
@AyushExel currently, video reading from supervison does not support batch operation. So making changes for video saving only.

ref: https://supervision.roboflow.com/latest/utils/video/#supervision.utils.video.get_video_frames_generator

### CODE REVIEW

**Comment by AyushExel** [comment]
Have you tested this manually? Could there any perf. slowdowns due to this? If not, I'll merge this

**Comment by hardikdava** [comment]
@AyushExel I haven't tested it atm. I will do it tonight.

**Comment by hardikdava** [comment]
@AyushExel Found issue in model name, difference between `-` and `_` in release checkpoint.
```
Failed to download dfine-n.pth: 404 Client Error: Not Found for url: https://github.com/ayushexel/trolo/releases/download/0.1.1/dfine-n.pth
```

**Comment by AyushExel** [comment]
@hardikdava its most like a verbose logging issue. It should check for both - and _ variants so the code should work even after this error. Or does it not work for you at all?

**Comment by hardikdava** [comment]
Small glimps of saved video
https://github.com/user-attachments/assets/bcd2694a-8fc9-4510-8c4f-a6cd8b1316b1

**Comment by hardikdava** [comment]
@AyushExel This PR ready to review.

**Comment by AyushExel** [comment]
Awesome! Is it ready to be merged?

**Comment by hardikdava** [comment]
@AyushExel Yes

**Pull request merged**
