### PR TITLE
Prediction annotation using supervision

### PR DESCRIPTION
**Pull request by hardikdava**
- added supervision package in deps
- predictions convert to supervision
- annotation drawing with supervision

### CODE REVIEW

**Comment by hardikdava** [comment]
Here are the predictions from old method and supervision method.

# old method:
output_master

# supervision method:
output_sv

**Comment by hardikdava** [comment]
@AyushExel Looks like something wrong in the base boxes resize function. Person boxes seems not accurate.

**Comment by AyushExel** [comment]
Yes the cropped person on the right? Yeah seems strange. Can you verify with some other example to confirm the problem or find the solution? Im away from the system for a bit. I'll take a look tonignt

**Comment by hardikdava** [comment]
@AyushExel  I could not find it. It will be very quick fix for you. I have following questions.

- where does this function [use](https://github.com/AyushExel/trolo/blob/276d9204159cb3047d316d37080194dad8d105dc/trolo/visualize.py#L7)?
- also this [one](https://github.com/AyushExel/trolo/blob/master/trolo/infer.py)?

**Comment by AyushExel** [comment]
both those files are now redundant and need to be removed. Feel free to delete them in this PR or I can also do it in my next PR

**Comment by hardikdava** [comment]
@AyushExel understood. I will handle it in this PR itself.

**Comment by hardikdava** [comment]
@AyushExel This PR is ready to review.

**Review by AyushExel — APPROVED** [review]

**Comment by AyushExel** [comment]
Awesome! Thanks

**Pull request merged**
